version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: rssagg-postgres
    environment:
      POSTGRES_DB: rssagg
      POSTGRES_USER: rssagg_user
      POSTGRES_PASSWORD: rssagg_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rssagg_user -d rssagg"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
